name: Build NekoStrap

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake unzip wget

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip -q android-ndk-r26d-linux.zip -d $HOME
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r26d" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake -B build -S . \
            -DANDROID_ABI="armeabi-v7a;arm64-v8a" \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -G Ninja

      - name: Build
        run: cmake --build build --target nekostrap

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nekostrap-libs
          path: build/**/*.so
